export const instanceListMock = {
  instances: [
    {
      id: 6541,
      status: 1,
      statusName: 'active',
      instanceId: 12,
      instanceName: 'Instance_12',
      regionName: 'EU',
    },
    {
      id: 6542,
      status: 2,
      statusName: 'pending',
      instanceId: 12,
      instanceName: 'Instance_12',
      regionName: 'AU',
    },
    {
      id: 6543,
      status: 2,
      statusName: 'pending',
      instanceId: 12,
      instanceName: 'Instance_12',
      planId: 6,
      regionName: 'AU',
    },
    {
      id: 6544,
      status: 1,
      statusName: 'active',
      instanceId: 12,
      instanceName: 'Instance_12',
      regionName: 'EU',
    },
    {
      id: 6545,
      status: 3,
      statusName: 'closed',
      instanceId: 25,
      instanceName: 'Instance_25',
      regionName: 'US',
    },
    {
      id: 6546,
      status: 1,
      statusName: 'active',
      instanceId: 25,
      instanceName: 'Instance_25',
      regionName: 'US',
    },
    {
      id: 6548,
      status: 1,
      statusName: 'active',
      instanceId: 25,
      instanceName: 'Instance_25',
      regionName: 'EU',
    },
    {
      id: 6549,
      status: 1,
      statusName: 'active',
      instanceId: 25,
      instanceName: 'Instance_25',
      regionName: 'AU',
    },
    {
      id: 6641,
      status: 1,
      statusName: 'active',
      instanceId: 59,
      instanceName: 'Instance_59',
      regionName: 'EU',
    },
    {
      id: 6642,
      status: 1,
      statusName: 'active',
      instanceId: 59,
      instanceName: 'Instance_59',
      regionName: 'US',
    },
    {
      id: 6643,
      status: 2,
      statusName: 'pending',
      instanceId: 59,
      instanceName: 'Instance_59',
      regionName: 'EU',
    },
    {
      id: 6644,
      status: 2,
      statusName: 'pending',
      instanceId: 59,
      instanceName: 'Instance_59',
      regionName: 'US',
    },
    {
      id: 6645,
      status: 3,
      statusName: 'closed',
      instanceId: 36,
      instanceName: 'Instance_36',
      regionName: 'EU',
    },
    {
      id: 6646,
      status: 3,
      statusName: 'closed',
      instanceId: 36,
      instanceName: 'Instance_36',
      regionName: 'AU',
    },
    {
      id: 6648,
      status: 1,
      statusName: 'active',
      instanceId: 36,
      instanceName: 'Instance_36',
      regionName: 'AU',
    },
    {
      id: 6649,
      status: 1,
      statusName: 'active',
      instanceId: 36,
      instanceName: 'Instance_36',
      regionName: 'US',
    },
    {
      id: 7001,
      status: 1,
      statusName: 'active',
      instanceId: 42,
      instanceName: 'Instance_42',
      regionName: 'EU',
    },
    {
      id: 7002,
      status: 2,
      statusName: 'pending',
      instanceId: 42,
      instanceName: 'Instance_42',
      regionName: 'US',
    },
    {
      id: 7003,
      status: 1,
      statusName: 'active',
      instanceId: 42,
      instanceName: 'Instance_42',
      regionName: 'US',
    },
    {
      id: 7004,
      status: 3,
      statusName: 'closed',
      instanceId: 42,
      instanceName: 'Instance_42',
      regionName: 'EU',
    },
    {
      id: 7005,
      status: 1,
      statusName: 'active',
      instanceId: 88,
      instanceName: 'Instance_88',
      regionName: 'EU',
    },
    {
      id: 7006,
      status: 3,
      statusName: 'closed',
      instanceId: 88,
      instanceName: 'Instance_88',
      regionName: 'US',
    },
    {
      id: 7008,
      status: 1,
      statusName: 'active',
      instanceId: 88,
      instanceName: 'Instance_88',
      regionName: 'EU',
    },

    {
      id: 7009,
      status: 2,
      statusName: 'pending',
      instanceId: 71,
      instanceName: 'Instance_71',
      regionName: 'EU',
    },
    {
      id: 7010,
      status: 1,
      statusName: 'active',
      instanceId: 71,
      instanceName: 'Instance_71',
      regionName: 'US',
    },
    {
      id: 7011,
      status: 3,
      statusName: 'closed',
      instanceId: 71,
      instanceName: 'Instance_71',
      regionName: 'AU',
    },
    {
      id: 7013,
      status: 1,
      statusName: 'active',
      instanceId: 53,
      instanceName: 'Instance_53',
      regionName: 'EU',
    },
    {
      id: 7014,
      status: 2,
      statusName: 'pending',
      instanceId: 53,
      instanceName: 'Instance_53',
      regionName: 'EU',
    },
    {
      id: 7015,
      status: 1,
      statusName: 'active',
      instanceId: 53,
      instanceName: 'Instance_53',
      regionName: 'US',
    },
    {
      id: 7016,
      status: 3,
      statusName: 'closed',
      instanceId: 53,
      instanceName: 'Instance_53',
      regionName: 'US',
    },
  ],
};
